import type { Metadata } from "next";

import Dock from "./components/Dock";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import SyncUser from "./components/SyncUser";
import ThemeProvider from "./components/ThemeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <ThemeProvider>
        <html lang="en">
          <body>
            <header className="flex justify-end items-center p-4 gap-4 h-16">
              <SignedIn>
                <UserButton
                  appearance={{
                    elements: {
                      userButtonAvatarBox: "w-10 h-10",
                      userButtonAvatarImage: "rounded-full",
                      userButtonUsername: "hidden",
                      userButtonProfile: "hidden",
                    },
                  }}
                />
                <SyncUser />
              </SignedIn>
            </header>
            <div className="text-base-content min-h-screen mb-12 container">
              {/* Show full app only when signed in */}
              <SignedIn>
                {children}
                <Dock />
              </SignedIn>

              {/* Show sign-in screen when signed out */}
              <SignedOut>
                <main className="flex justify-center items-center min-h-[80vh]">
                  <SignInButton />
                  <SignUpButton />
                </main>
              </SignedOut>
            </div>
          </body>
        </html>
      </ThemeProvider>
    </ClerkProvider>
  );
}
